### ISSUE TITLE
US 01.05.01 As an organizer, I want to track real-time attendance and receive alerts for important milestones.

### ISSUE THREAD

**Issue by sdbelhum** [CMPUT301W24T29/QuickScanQuestPro#14]
### Acceptance Criteria
- Button in the event details when an organizer views their event that lets them see the number of people checking into their event
- When an "important milestone" is crossed (number of attendees checked in), the organizer receives a notification on their phone

Story Points: 2
Risk Level: Medium

### Released for halfway point?
No

### Progress / Completion Criteria
- [x] Code
  - [x] Organizer has Textview that shows the current number of attendees for each event, in event details
  - [ ] TextView is updated when new atendee atends event
  - [ ] Organizer recieves notifications for number atendees for each event, depending on certain thresholds, possibly customizable by the organizer
  - [ ] (Possibility) Having organizer enter goal attendance when creting an event and having percentages of that as goals.
- [ ] Javadocs
- [ ] Tests
- [ ] UI Mockup
- [ ] Storyboard
- [ ] UML

**Comment by alastairvox** [comment]
Will need to work with joshua for the notification component of this user story

**Comment by jojojojimmy** [comment]
added an attendee button only visible to those who are the organisers of the event.

**Comment by jojojojimmy** [comment]
done most of it, just have a doubt regarding what the milestones should be and whether or not the organizer should get them as push notification or only when they view the attendees list!
