### ISSUE TITLE
US 03.02.01 As a user, I want the option to enable or disable geolocation tracking for event verification.

### ISSUE THREAD

**Issue by josephhdu** [CMPUT301W24T29/QuickScanQuestPro#7]
US 03.02.01 As a user, I want the option to enable or disable geolocation tracking for event verification.

### Acceptance Criteria
- In the user profile, can click a button to enable or disable geolocation tracking for event verification, meaning when a user checks into an event by scanning a code, the location of the user is recorded

Story Points: 5
Risk Level: Low

### Released for halfway point?
No

### Progress / Completion Criteria
- [x] Code
  - [x] add User class bool "geolocation" (default false)
  - [x] hook up the geolocation on/off switch in the user profile page to location permission request and toggle User bool
  - [x] create GeolocationService that can get current location and handle location permissions
  - [x] store and retrieve user geolocation setting from database
  - [x] in scanner: if geolocation true for user, retrieve current device location
  - [x] store user location with checkin
- [x] Javadocs
- [x] Tests
  - [x] tests will require adding text to test setup readme: android emulator must have mock location enabled
  - [x] test that when checking in with User bool disabled, event stored checkin but no location
  - [x] add permission request override when toggling the boolean to immediately grant like the camera perms
  - [x] test that when checking in with User bool enabled, event stored checkin WITH a location
- [x] UI Mockup
- [x] Storyboard
- [x] UML

**Comment by alastairvox** [comment]
Clarification requested: https://eclass.srv.ualberta.ca/mod/forum/discuss.php?d=2448364

**Comment by alastairvox** [comment]
need clarification still on if this is "verification" or just needs to be recorded :/
